name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Release binaries
        path: ./bin/release/netcore3.0
